- name: defualtfilter
  hosts: web
  tasks:
     - name: defaulfikter
       ansible.builtin.debug:
         msg: "{{manju | default(5)}}"

     - name: defaulfikter
       vars:
         fruits: " banana , apply "
       ansible.builtin.debug:
         msg: "{{ fruits | split(',') }}"

     - name: convert map to list
       vars:
         COURCE:
           name: Devops
           duration: 12
       ansible.builtin.debug:
         msg: "{{ COURCE | dict2items  }}"

     - name: convert map to list
       vars:
         tags:
           - key: Application
             value: payment
           - key: Environment
             value: dev
       ansible.builtin.debug:
         msg: "{{ COURCE | items2dict }}"
        
