- name: install nginx
  hosts: web
  become: yes
  tasks:
     - name: install nginx in radhat
       ansible.builtin.dnf:
         name: nginx
         state: present
       when: ansible_os_family == "RedHat"
       


