- name: loop install 
  hosts: web
  become: yes
  tasks:
     - name: loop install  in radhat
       ansible.builtin.dnf:
         name: "{{ item.name }}"
         state: "{{ item.state }}"
       loop:
         - { name: 'nginx' , state: 'present'} 
         - { name: 'gem' , state: 'absent'}  
       


       


