- name: loop install 
  hosts: web
  become: yes
  tasks:
     - name: loop install  in radhat
       ansible.builtin.dnf:
         name: "{{ item }}"
         state: present
         loop:
           - nginx
           - gem
       


       


