- name : Lunch Ec2 and Route 53
  hosts: local
  connection: local
  gather_facts: yes
  tasks: 
   - name: Install bottle for Python 3.3 specifically, using the 'pip3.3' executable
     ansible.builtin.pip:
       name: "{{ item }}"
       executable: pip3.9
     loop:
      - boto3
      - botocore

   - name: start an instance with a public IP address
     amazon.aws.ec2_instance:
       name: "{{ item }}"
       vpc_subnet_id: subnet-0c26e13f782edfff0
       instance_type: t2.micro
       security_group: sg-0a66b33908bd8eb94
       image_id: ami-09c813fb71547fc4f
     register: ec2_info
     loop:
       - mysql
       - backend
       - web

   - name: Gather EC2 remote facts.
     ec2_instance_info:
        filters:
           availability-zone: us-east-1d
     register: ec2_instance_facts
   -  set_fact:
         msg: "{{ ec2_instance_facts | json_query('instances[*].private_ip_address') }} "
   - debug: var=msg
    
  