- name: install nginix
  hosts: web
  become: yes
  tasks:
  - name: install 
    ansible.builtin.package:
      name: nginx
      state: present

  - name: servcie
    ansible.builtin.service:
    name: nginx
    state: started 
    enabled: yes
