- name: tasklevel varaibles
  hosts: web
  vars:
   name : manju
  tasks:
   - name : task level variables
     vars:
      name : sudheer
     ansible.builtin.debug:
      msg: "connecting local {{name}}"
