- name: print numbers
  hosts: local
  connection: local
  vars:
   my_number: 10
  tasks:
   - name: print if number greter than 10
     ansible.builtin.debug:
       msg: "print : {{my_number}} is greater than 10"
     when: my_number > 10